name: CD Pipeline

on:
  push:
    branches: [ main ]        # Ejecuta el pipeline automáticamente cuando hay cambios en la rama 'main'
  pull_request:
    branches: [ main ]        # Ejecuta el pipeline cuando se abre un Pull Request hacia 'main'

env:
  DOTNET_VERSION: '9.0.x'
  AZURE_WEBAPP_NAME: 'sample-api-ava'
  SOLUTION_PATH: './SampleApiApp.sln'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest    # Usa una máquina virtual Ubuntu como agente de ejecución

    steps:
      # Descarga el código fuente del repositorio
      - uses: actions/checkout@v4

      - name: Cachear paquetes NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Instala el SDK de .NET 9.x en el agente
      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}   
      
      - name: Restaurar dependencias
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      # Compila el proyecto en modo Release
      - name: Compilar
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      # Ejecuta las pruebas del proyecto (sin recompilar)
      - name: Ejecutar pruebas
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publicar aplicación
        run: |
          dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build

  deploy:
    name: Deploy to Azure Web App
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      # Usa la acción oficial de Azure para desplegar la aplicación web
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}